Added the endpoint to return the list of requests to join a given league
ladoe00/league-management pull request #3
Opened 2018-04-23 01:36 UTC by pjgaudr

2018-04-25 10:23 UTC, ladoe00 requested changes

2018-04-25 10:23 UTC, ladoe00 commented on src/main/java/org/nnhl/resources/LeagueResource.java
> +    public Response getLeagueRequests(
We should protect this resource with ADMIN or MANAGER role....  I need to improve the handling of MANAGER role for  a specific league.

2018-04-25 10:23 UTC, ladoe00 commented on src/main/java/org/nnhl/resources/LeagueResource.java
> +            leagueDao.deleteLeagueRequest(leagueId, playerId);
Let's make this part of a transaction.  If the delete fails, the join should not be committed.  I have an example in one of my DAO.

2018-04-26 01:25 UTC, pjgaudr commented
Added @Transaction and @RolesAllowed annotations!

2018-04-26 02:28 UTC, pjgaudr commented
I can't make calls using swagger anymore for protected resources???

2018-05-13 01:59 UTC, merged